In [39]:
import numpy as np
np.set_printoptions(precision=3)

In [45]:
A = np.zeros((4,4))
for i in range(4):
    A[i,i] = 1
for i in range(3):
    A[i,i+1] = 1
w,v = np.linalg.eig(A)

In [47]:
A

array([[1., 1., 0., 0.],
       [0., 1., 1., 0.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.]])

In [50]:
v

array([[ 1.000e+00, -1.000e+00,  1.000e+00, -1.000e+00],
       [ 0.000e+00,  2.220e-16, -2.220e-16,  2.220e-16],
       [ 0.000e+00,  0.000e+00,  4.930e-32, -4.930e-32],
       [ 0.000e+00,  0.000e+00,  0.000e+00,  1.095e-47]])

In [51]:
np.matmul(A,v)

array([[ 1.000e+00, -1.000e+00,  1.000e+00, -1.000e+00],
       [ 0.000e+00,  2.220e-16, -2.220e-16,  2.220e-16],
       [ 0.000e+00,  0.000e+00,  4.930e-32, -4.930e-32],
       [ 0.000e+00,  0.000e+00,  0.000e+00,  1.095e-47]])

In [31]:
theta = 0.4
A = np.array([[np.cos(theta),-np.sin(theta)],[np.sin(theta),np.cos(theta)]])

In [32]:
_,s,_ = np.linalg.svd(A)
s.sort()
print(s)
val,vec = np.linalg.eig(A.T.dot(A))
#est = np.sqrt(val * np.conj(val))
est = np.sqrt(val)
est.sort()
print(est)

[1. 1.]
[1. 1.]


In [35]:
print(A)

[[ 0.921 -0.389]
 [ 0.389  0.921]]


In [34]:
val,vec = np.linalg.eig(A)
print(val)
print(vec)

[0.921+0.389j 0.921-0.389j]
[[0.707+0.j    0.707-0.j   ]
 [0.   -0.707j 0.   +0.707j]]


In [36]:
A.dot(vec)

array([[0.651+0.275j, 0.651-0.275j],
       [0.275-0.651j, 0.275+0.651j]])

In [38]:
val * vec

array([[0.651+0.275j, 0.651-0.275j],
       [0.275-0.651j, 0.275+0.651j]])