In [1]:
import torch

In [12]:
a = torch.tensor([3.], requires_grad=True)
loss = a**2
loss.backward(create_graph=True)
print(a.grad)
lossloss = a.grad
print(a.grad)
a.grad.data.zero_()
lossloss.backward();

tensor([6.], grad_fn=<CopyBackwards>)
tensor([6.], grad_fn=<CopyBackwards>)


In [13]:
a.grad

tensor([2.], grad_fn=<CopyBackwards>)